import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Sonner from '@/components/providers';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="font-gilroy light">
      <body>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="light">
            {/* <Navbar /> */}
            <main>{children}</main>
            <Sonner />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
